baseURL = "/"
languageCode = "en-us"
title = "[Any tech] in 100 days"
theme = "kube"
description = "Why just learn anything in 100 days! We must master it."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "in100daysOrg"
  github = "in100daysOrg"
  twitter = "in100daysOrg"
  email = "in100days@avichaganti.com"

[[menu.main]]
    name = "Technologies"
    weight = -200
    url = "/tech/"

#[[menu.main]]
#    name = "About"
#    weight = -100
#    url = "/about/"

#[[menu.main]]
#    name = "Faq"
#    weight = -100
#    url = "/faq/"
